apiVersion: apps/v1
kind: Deployment
metadata:
  name: bye-deployment
  labels:
    app: bye
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bye
  template:
    metadata:
      labels:
        app: bye
    spec:
      containers:
        - name: bye
          image: ziemowits/bye:R.2024-3.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5